variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
      
stages:
  - module-pipelines
  - argocd-deploy
#depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  
backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

backend-report:
  stage: module-pipelines
  trigger:
    include:
      - "/backend-report/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend-report/**/*

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

deploy:
  stage: argocd-deploy
  trigger:
    include:
      - "/argocd/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - argocd/**/*