GRANT USAGE ON SCHEMA public to admin_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin_user;
GRANT ALL ON ALL TABLES IN SCHEMA public TO admin_user;
