GRANT USAGE ON SCHEMA public to read_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read_user;
GRANT CONNECT ON DATABASE sausage_store_db to read_user;

GRANT USAGE ON SCHEMA public to read_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO read_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_user;