backend:
  image: gitlab.praktikum-services.ru:5050/stb101201/sausage-store/sausage-backend
  tag: latest
  imagePullPolicy: IfNotPresent
  replicas: 3
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20%
  containerPort: 8080
  flywayMigrate: "false"
  logPath: /tmp
  reportPath: /tmp

backend-report:
  image: gitlab.praktikum-services.ru:5050/stb101201/sausage-store/sausage-report-backend
  tag: latest
  imagePullPolicy: IfNotPresent
  strategy:
    type: Recreate
  containerPort: 8081

frontend:
  image: gitlab.praktikum-services.ru:5050/stb101201/sausage-store/sausage-frontend
  tag: latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  revisionHistoryLimit: 15
  fqdn: stanislav-bitkov-1.k8s.praktikum-services.tech
  httpPort: 80
  ingressBackendName: backend
  ingressBackendPort: 8080